from q4b import get_min_allocation_grid

print()
print('-' * 20)
print("Test Case 1: get_min_allocation_grid([[2, 2], [2, 2]])")
result = get_min_allocation_grid([[2,2], [2,2]])
print('Expected: [[1, 1], [1, 1]]')
print('Actual:  ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))
print()

print('-' * 20)
print("Test Case 2: get_min_allocation_grid([[1, 2, 3], [2, 3, 4]])")
result = get_min_allocation_grid([[1,2,3], [2,3,4]])
print('Expected: [[1, 2, 3], [2, 3, 4]]')
print('Actual:  ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))
print()

print('-' * 20)
print("Test Case 3: get_min_allocation_grid([[8, 7, 4], [6, 4, 2]])")
result = get_min_allocation_grid([[8,7,4], [6,4,2]])
print('Expected: [[4, 3, 2], [3, 2, 1]]')
print('Actual:  ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))
print()

print('-' * 20)
print("Test Case 4: get_min_allocation_grid([[1, 3, 3, 1], [2, 2, 1, 0]])")
result = get_min_allocation_grid([[1,3,3,1], [2,2,1,0]])
print('Expected: [[1, 4, 3, 2], [2, 3, 2, 1]]')
print('Actual:  ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))
print()

print('-' * 20)
# increasing mixed with decreasing both in row and columns
print("Test Case 5: get_min_allocation_grid([[1, 2, 3, 1], [0, 1, 5, 2], [2, 3, 4, 1]])")
result = get_min_allocation_grid([[1, 2, 3, 1], [0, 1, 5, 2], [2, 3, 4, 1]])
print('Expected: [[2, 3, 4, 1], [1, 2, 5, 2], [2, 3, 4, 1]]')
print('Actual:  ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))
print()

print('-' * 20)
# mixed order with equals
print("Test Case 6: get_min_allocation_grid([[3, 2, 1, 1, 7], [0, 1, 7, 2, 2], [2, 4, 4, 1, 5], [6, 5, 4, 4, 5]]))")
print()
result = get_min_allocation_grid([[3, 2, 1, 1, 7],[0, 1, 7, 2, 2],[2, 4, 4, 1, 5], [6, 5, 4, 4, 5]])
print('Expected: ', [[4, 3, 1, 1, 2], [1, 2, 3, 2, 1], [2, 3, 2, 1, 2], [5, 4, 1, 2, 3]])
print('Actual:   ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))
print()

print('-' * 20)
