from q4a import get_min_allocation

print()
print('-' * 20)
# N==1
print("Test Case 1: get_min_allocation([3]))")
result = get_min_allocation([3])
print('Expected: [1]')
print('Actual:  ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))

print()
print('-' * 20)
print("Test Case 2: get_min_allocation([0, 3, 5])")
result = get_min_allocation([0, 3, 5])
print('Expected: [1, 2, 3]')
print('Actual:  ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))

print()
print('-' * 20)
print("Test Case 3: get_min_allocation([9, 6, 5, 2])")
result = get_min_allocation([9, 6, 5, 2])
print('Expected: [4, 3, 2, 1]')
print('Actual:  ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))

print()
print('-' * 20)
print("Test Case 4: get_min_allocation([0, 3, 3, 5])")
result = get_min_allocation([0, 3, 3, 5])
print('Expected: [1, 2, 1, 2]')
print('Actual:  ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))

print()
print('-' * 20)
print("Test Case 5: get_min_allocation([7, 6, 6, 3])")
result = get_min_allocation([7, 6, 6, 3])
print('Expected: [2, 1, 2, 1]')
print('Actual:  ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))

print()
print('-' * 20)
print("Test Case 6: get_min_allocation([2, 6, 5, 6, 2])")
result = get_min_allocation([2, 6, 5, 6, 2])
print('Expected: ', [1, 2, 1, 2, 1])
print('Actual:   ', result)
print("Expected type of returned value: <class 'list'>")
print('Actual type of returned value:   ' + str(type(result)))

print()
print('-' * 20)
