# The code here are used in the test scripts
# You do not need to use them in your code
pokedex_ref_full = [{'record_id': 0, 'pokedex_number': 1, 'name': 'Bulbasaur', 'type_1': 'Grass', 'type_2': 'Poison', 'height_m': 0.7, 'weight_kg': 6.9, 'hp': 45},
{'record_id': 1, 'pokedex_number': 2, 'name': 'Ivysaur', 'type_1': 'Grass', 'type_2': 'Poison', 'height_m': 1.1, 'weight_kg': 13.1, 'hp': 60},
{'record_id': 2, 'pokedex_number': 3, 'name': 'Venusaur', 'type_1': 'Grass', 'type_2': 'Poison', 'height_m': 2.1, 'weight_kg': 100.1, 'hp': 80},
{'record_id': 3, 'pokedex_number': 3, 'name': 'Mega Venusaur', 'type_1': 'Grass', 'type_2': 'Poison', 'height_m': 2.4, 'weight_kg': 155.5, 'hp': 80},
{'record_id': 4, 'pokedex_number': 4, 'name': 'Charmander', 'type_1': 'Fire', 'type_2': None, 'height_m': 0.6, 'weight_kg': 8.5, 'hp': 39},
{'record_id': 5, 'pokedex_number': 5, 'name': 'Charmeleon', 'type_1': 'Fire', 'type_2': None, 'height_m': 1.1, 'weight_kg': 19.1, 'hp': 58},
{'record_id': 6, 'pokedex_number': 6, 'name': 'Charizard', 'type_1': 'Fire', 'type_2': 'Flying', 'height_m': 1.7, 'weight_kg': 90.5, 'hp': 78},
{'record_id': 7, 'pokedex_number': 6, 'name': 'Mega Charizard X', 'type_1': 'Fire', 'type_2': 'Dragon', 'height_m': 1.7, 'weight_kg': 110.5, 'hp': 78},
{'record_id': 8, 'pokedex_number': 6, 'name': 'Mega Charizard Y', 'type_1': 'Fire', 'type_2': 'Flying', 'height_m': 1.7, 'weight_kg': 100.5, 'hp': 78},
{'record_id': 9, 'pokedex_number': 7, 'name': 'Squirtle', 'type_1': 'Water', 'type_2': None, 'height_m': 0.5, 'weight_kg': 9.1, 'hp': 44},
{'record_id': 10, 'pokedex_number': 8, 'name': 'Wartortle', 'type_1': 'Water', 'type_2': None, 'height_m': 1.1, 'weight_kg': 22.5, 'hp': 59},
{'record_id': 15, 'pokedex_number': 12, 'name': 'Butterfree', 'type_1': 'Bug', 'type_2': 'Flying', 'height_m': 1.1, 'weight_kg': 32.1, 'hp': 60},
{'record_id': 212, 'pokedex_number': 172, 'name': 'Pichu', 'type_1': 'Electric', 'type_2': None, 'height_m': 0.3, 'weight_kg': 2.1, 'hp': 20},
{'record_id': 215, 'pokedex_number': 175, 'name': 'Togepi', 'type_1': 'Fairy', 'type_2': None, 'height_m': 0.3, 'weight_kg': 1.5, 'hp': 35},
{'record_id': 369, 'pokedex_number': 311, 'name': 'Plusle', 'type_1': 'Electric', 'type_2': None, 'height_m': 0.4, 'weight_kg': 4.2, 'hp': 60},
{'record_id': 489, 'pokedex_number': 412, 'name': 'Burmy', 'type_1': 'Bug', 'type_2': None, 'height_m': 0.2, 'weight_kg': 3.4, 'hp': 40},
{'record_id': 496, 'pokedex_number': 417, 'name': 'Pachirisu', 'type_1': 'Electric', 'type_2': None, 'height_m': 0.4, 'weight_kg': 3.9, 'hp': 60},
{'record_id': 506, 'pokedex_number': 427, 'name': 'Buneary', 'type_1': 'Normal', 'type_2': None, 'height_m': 0.4, 'weight_kg': 5.5, 'hp': 55},
{'record_id': 565, 'pokedex_number': 479, 'name': 'Wash Rotom', 'type_1': 'Electric', 'type_2': 'Water', 'height_m': 0.3, 'weight_kg': 0.3, 'hp': 50},
{'record_id': 569, 'pokedex_number': 480, 'name': 'Uxie', 'type_1': 'Psychic', 'type_2': None, 'height_m': 0.3, 'weight_kg': 0.3, 'hp': 75},
{'record_id': 659, 'pokedex_number': 562, 'name': 'Yamask', 'type_1': 'Ghost', 'type_2': None, 'height_m': 0.5, 'weight_kg': 1.5, 'hp': 38},
{'record_id': 700, 'pokedex_number': 602, 'name': 'Tynamo', 'type_1': 'Electric', 'type_2': None, 'height_m': 0.2, 'weight_kg': 0.3, 'hp': 35},
{'record_id': 766, 'pokedex_number': 659, 'name': 'Bunnelby', 'type_1': 'Normal', 'type_2': None, 'height_m': 0.4, 'weight_kg': 5.1, 'hp': 38},
{'record_id': 871, 'pokedex_number': 746, 'name': 'Wishiwashi Solo Form', 'type_1': 'Water', 'type_2': None, 'height_m': 0.2, 'weight_kg': 0.3, 'hp': 45},
{'record_id': 921, 'pokedex_number': 794, 'name': 'Buzzwole', 'type_1': 'Bug', 'type_2': 'Fighting', 'height_m': 2.4, 'weight_kg': 333.6, 'hp': 107},
{'record_id': 1002, 'pokedex_number': 871, 'name': 'Pincurchin', 'type_1': 'Electric', 'type_2': None, 'height_m': 0.3, 'weight_kg': 1.1, 'hp': 48}]

